### ISSUE TITLE
구간변경에서의 누적합

### ISSUE THREAD

**Issue by yujin1292** [yujin1292/BreakingCodingTest#106]
누적합을 이용해 구간의 값을 변경하는 문제를  간단하게 풀어내는 방법에 대해서 생각해보려고 합니다.

## 1차원 누적합

_*a..b ( a≤ i ≤ b 구간 ) 으로 표현하겠습니다_ 

(a..b) 구간에 V 만큼의 값의 변화를 주는 상황을 생각해봅시다 ! ! 
일반적으로 생각하게 되면 구간의 길이만큼 순회하며 값을 변화시키게 됩니다. 
~~~ kotlin
for(  i in a..b)
  arr[i] += V
~~~
즉,  O(b - a) → O(N) 의 시간복잡도로 배열에 변화를 주게 됩니다. 

이번에는 여러번 연산을 진행하는 상황을 생각해 보도록 하겠습니다. 
~~~
만약 size가 1,000,000 이고, 0으로 초기화 되어있는 배열에 특정

(3 .. 5124) 에 10 을 더하고, (2 .. 142 ) 에 -2를 더하는 등 1,000 개의 연산을 진행하게된다면 시간이 얼마나 걸릴까요 ?
~~~

하나의 연산을 하나씩 진행해주는데 O(N) 의 시간복잡도 이므로 연산의수를 M이라 하면 시간 복잡도는 O(N*M) 입니다.
즉, 최악의경우 1,000,000(배열 size)  * 1,000(연산의수) = 1,000,000,000 으로 매우 긴 연산이 될것입니다.
따라서 연산을 일일히 해줄것이 아니라 간편하게 진행할 방법이 필요합니다 ! !

---

| 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|:--:|:--:| :--:|:--:|:--:| :--:|:--:|
| 0 | 1 | 0 | 0 | 0 | 0 | 0 |

이란 배열이 있고 누적합을 구하게 되면 

| 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|:--:|:--:| :--:|:--:|:--:| :--:|:--:|
| 0 | 1 | 1 | 1 | 1| 1 | 1 |

이 됩니다 !

</br>

이 상황을 눈여겨 보면 1번 자리에 있는 값들로 인해 뒤에있는 값들에 연쇄적으로 작용하고있는것을 볼 수 있습니다.

한번더 응용하면,

| 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|:--:|:--:| :--:|:--:|:--:| :--:|:--:|
| 0 | -2 | 0 | 0 | 0 | 0 | 0 |

이란 배열이 있고 누적합을 구하게 되면 

| 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|:--:|:--:| :--:|:--:|:--:| :--:|:--:|
| 0 | -2 | -2 | -2 | -2| -2 | -2 |

이 되겠죠?

</br>

**혹시 눈치채셨나요 ? ? ? !! !**  

만약 1~3 자리에 +3을 해야한다면?

배열을 **시작과 끝점**+1 에 변화될 값을 넣어준후

| 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|:--:|:--:| :--:|:--:|:--:| :--:|:--:|
| 0 | 3 | 0 | 0 | -3 | 0 | 0 |

누적합을 계산하면

| 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|:--:|:--:| :--:|:--:|:--:| :--:|:--:|
| 0 | 3 | 3 | 3 | 0 | 0 | 0 |

대박! ! 두번의 연산 + 한번의 누적합으로 O(N) 특정 구간의 값을 변화 시킬수 있게 되었습니다.

---

다시 위에서 언급한 문제를 다시 풀어보겠습니다. 

~~~
만약 size가 1,000,000 이고, 0으로 초기화 되어있는 배열에 특정

(3 .. 5124) 에 10 을 더하고, (2 .. 142 ) 에 -2를 더하는 등 1,000 개의 연산을 진행하게된다면 시간이 얼마나 걸릴까요 ?
~~~

우리는 이제 시작점과 끝점에 변하는 값을 저장하고 한번의 누적합을 진행할겁니다.
따라서 1,000 개의 연산의 시작과 끝만 값을 변경하고 한번의 누적합을 진행하니
2*1,000 + 1,000,000 번의 과정이 있겠고 즉 O(N + M) 의 시간복잡도를 가지게 됩니다.

## 2차원 배열
이를 응용해서 2차원 배열에도 적용할 수있습니다 !

2차원 배열에서의 누적합은
![image](https://user-images.githubusercontent.com/27190708/160374185-b61c8ace-4d9d-48c9-a2a5-1abadd121ea9.png)

의 형태로, 가로로 다 누적해주고 세로로 누적해주면 됩니다..

| 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|:--:|:--:| :--:|:--:|:--:| :--:|:--:|
|0|0|0|0|0|0|0|
| 0 | 1 | 0 | 0 | 0 | 0 | 0 |
| 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| 0 | 0 | 0 | 0 | 0 | 0 | 0 |

의 누적합을 구하면?

| 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|:--:|:--:| :--:|:--:|:--:| :--:|:--:|
|0|0|0|0|0|0|0|
|0|1|1|1|1|1|1|
|0|1|1|1|1|1|1|
|0|1|1|1|1|1|1|

의 형태인데 특정 지점을 기준으로 퍼저나가는 형태로 누적되죠? ? 

이러한 성질을 이용해서 특정 구간의 값을 변경해봅시다!
왼쪽상단점 (1,1) ~  오른쪽 하단점( 2, 3 ) 의 구간에 +4 를 계산해보도록 응용하면 
아래처럼 구간의 시작과 끝부분을 조작해줍니다!

| 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|:--:|:--:| :--:|:--:|:--:| :--:|:--:|
|0|0|0|0|0|0|0|
|0|4|0|0|-4|0|0|
|0|0|0|0|0|0|0|
|0|-4|0|0|4|0|0|

이 배열을 누적합하면

| 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|:--:|:--:| :--:|:--:|:--:| :--:|:--:|
|0|0|0|0|0|0|0|
|0|4|4|4|0|0|0|
|0|4|4|4|0|0|0|
|0|0|0|0|0|0|0|

짠 ! ! (1,1) ~ ( 2,3) 구간의 값이 변했습니다..!

---
마무리를 어떻게해야할지모르겠네요
어쨋든 재밌는 팁이었죠?.. 아주 유용하답니다

**Comment by jeongiin** [comment]
누적 합의 의미는 이전 값 + 현재값이라 

| 0 | 1 | 2 | 3 | 4 | 5 | 6 |
|:--:|:--:| :--:|:--:|:--:| :--:|:--:|
|0|0|0|0|0|0|0|
| 0 | 1 | 0 | 0 | 0 | 0 | 0 |
| 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| 0 | 0 | 0 | 0 | 0 | 0 | 0 |

배열의 누적값이 (0,1) 뒤가 전부 1로 채워지는 거죠???
원소값이 0이 될수도 있어서 0이 더해질수도 있다는 점을 간과하고 있었네요;;
완전 꿀팁!!! 이 게시물 퍼가요~❤

**Comment by yujin1292** [comment]
@jeongiin 
네 맞아요~  사실 (1,1)자리인데... Row 인덱스를 안적으니 좀 헷갈리게 적어놓은것같네여 하하 

누적합을 보통은 ` s[i][j] = s[i][j-1] + s[i-1][j] - s[i-1][j-1] ` 로 표현하기도 하더라고요!
가로로도 누적하고 세로로도 누적한다! 이렇게 생각하면 편리합니다..!

그리고 0이 더해질수도 있다 보다는 특정 값에 변화를 주면 그 변화가 퍼져나간다?..가 핵심


---

그냥 비어있던 배열에 의 배열에  `arr[1][1] += 1` 라는 변화를 줘보면 아래처럼변한다는거죵


0 | 1 | 2 | 3 | 4 | 5 | 6
-- | -- | -- | -- | -- | -- | --
0 | 0 | 0 | 0 | 0 | 0 | 0
0 | 0 | 0 | 0 | 0 | 0 | 0
0 | 0 | 0 | 0 | 0 | 0 | 0
0 | 0 | 0 | 0 | 0 | 0 | 0

👇 `arr[1][1] += 1`

0 | 1 | 2 | 3 | 4 | 5 | 6
-- | -- | -- | -- | -- | -- | --
0 | 0 | 0 | 0 | 0 | 0 | 0
0 | **+1** | 0 | 0 | 0 | 0 | 0
0 | 0 | 0 | 0 | 0 | 0 | 0
0 | 0 | 0 | 0 | 0 | 0 | 0

👇누적합

0 | 1 | 2 | 3 | 4 | 5 | 6
-- | -- | -- | -- | -- | -- | --
0 | 0 | 0 | 0 | 0 | 0 | 0
0 | +1 | +1 | +1 | +1 | +1 | +1
0 | +1 | +1 | +1 | +1 | +1 | +1
0 | +1 | +1 | +1 | +1 | +1 | +1

누적합에서는 +1의 여파가 이렇게 퍼져나간다?? 
이렇게 이해하시면 좀더 좋을것같아여

**Comment by yujin1292** [comment]
@jeongiin 

편의상 0으로 초기화되어있는 배열을 생각했는데 아래같은 경우도 생각해보면 좀 더 편할거에요
|arr|0 | 1 | 2 | 3 | 4 | 5 | 6
--|-- | -- | -- | -- | -- | -- | --
|**0**|0|1|0|1|0|1|0|
|**1**|1|2|1|2|1|2|1|
|**2**|2|3|2|3|2|3|2|

👇누적합

sum| 0 | 1 | 2 | 3 | 4 | 5 | 6
--| -- | -- | -- | -- | -- | -- | --
|**0**|0|1|1|2|2|3|3|
|**1**|1|4|5|8|9|12|13|
|**2**|3|9|12|18|21|27|30|

---

###  arr[1][1] -= 2 로 값 변화를줌

arr| 0 | 1 | 2 | 3 | 4 | 5 | 6
--| -- | -- | -- | -- | -- | -- | --
|**0**|0|1|0|1|0|1|0|
|**1**|1|0|1|2|1|2|1|
|**2**|2|3|2|3|2|3|2|

👇변경 후 누적합

sum | 0 | 1 | 2 | 3 | 4 | 5 | 6
--| -- | -- | -- | -- | -- | -- | --
|**0**|0|1|1|2|2|3|3|
|**1**|1|2|3|6|7|10|11|
|**2**|3|7|10|16|19|25|28| 

---

변경 전 누적합 값에서 -=2의 연산이 퍼져나갔음

**Comment by jeongiin** [comment]
퍼져나가는걸 생각도 못했네요..! 넘나 친절하고 자세한 설명 감사합니다!!
