### ISSUE TITLE
3주차 과제 2110

### ISSUE THREAD

**Issue by arami98** [yujin1292/BreakingCodingTest#30]
2110번 문제 풀이방법 수업시간에 다룬 것 같은데 제가 참여를 못해서 ㅠㅠ 흑 설명 한번만 부탁드립니다..!!

**Comment by yujin1292** [comment]
이분 탐색을 진행하기 위해서는 `어떤 변수` 의 범위를 탐색해야 하고, 변수의 `값에 따라 범위를 조절할수있는 근거`가 있어야 합니다!

전에 풀었던 나무 자르는 문제 같은경우는, `절단기의 길이`를 조절했고, `잘려진 나무의 양`에 따라서 절단기 길이의 범위를 조절했었어요

이번 문제같은경우 잘 보게되면, 공유기를 설치하게 되는데  `가장 인접한 두 공유기 사이의 거리를 가능한 크게 ` 해야합니다!

그러면 힌트가 생겼죠 지금 이분 탐색해야할 대상은 `설치된 공유기 거리중 가장 인접한 거리` 입니다
그런데 범위를 조절을 어떻게 할까요?...

지정된 값으로 공유기를 직접 설치 해 나아가고, `설치된 공유기의 개수`로 확인할 수 있습니다

문제의 예제 1 로 확인해볼게요

집의 위치가 아래와 같습니다 ( 정렬 했음 )
`1` `2` `4` `8` `9` 
이때 공유기가 가질수있는 최대 거리는 1과 9 사이의 거리겠죠?
따라서 start를 0, end 를 8 로 두고 이분탐색을 진행합니다.

첫번째 집에는 무조건 공유기를 설치한다고 가정해볼게요.
mid 값은 4 이므로 4이상의 거리에 공유기를 설치해야합니다.
따라서 `1`과의 거리가 4이상 떨어진곳이 `8`밖에없으므로 `8`에 설치, `8`과 4 이상 떨어진곳이 없으므로
`1`과 `8` 에 공유기가 설치됩니다.

따라서 mid 가 4 인경우 공유기가 두개 설치되었고, 더많은 공유기를 설치해야하기 때문에
거리를 좁혀야합니다.

정리하면, 
1. `설치된 공유기 < 설치해야할 공유기`   ->더많이 설치해야 하기때문에 범위를 좁힙니다
2. `설치된 공유기 >= 설치해야할 공유기` -> 범위를 넓힙니다. 

여기서 2번 문항이 조금 이상하다고 생각할 수 있는데요
`딱 C개 설치한것이 아니라 그 이상을설치해도 정답이라고 볼 수있는가?!` 라고 의문이 들수있어요
제가 그랬고요.. ㅎㅎ
그 이상을 설치해도 정답이 됩니다! 왜냐면 C개 까지만 설치하고 그 이상은 그냥 설치 안하면 되거든요

만약에 아래처럼 7개 설치했고 4개만 설치해야한다면 뒤에 세개를 그냥 설치안하면 되잖아요 ㅋㅋ
ㅇ ㅇ ㅇ ㅇ  x  x  x 

---

세줄 요약을 하자면 아래와 같고 이해 안되는 부분이있다면 다시 코맨트 남겨주세요~

1. 이분 탐색할 변수는 `가장 인접한 공유기사이의 거리` 이다.
2. 변수의 범위 설정은 `해당 거리로 설치한 공유기의 개수` 이다.
3. 공유기를 설치하기 위해서 첫 집(가장 거리가 작은 집)은 설치했다는 가정 하에 개수를 세어본다

**Comment by arami98** [comment]
2번 문항이 헷갈렸는데 설명 보고 이해 완전 됐네요! 문제 해결 했습니다 감사합니다~!!

**Comment by yujin1292** [comment]
네네 PR이랑 연결해놓아서 PR 머지되면 아마 이 이슈 Close 될거에요~
