### ISSUE TITLE
1991 트리 순회 문제

### ISSUE THREAD

**Issue by arami98** [yujin1292/BreakingCodingTest#31]
트리를 vector를 이용한 인접 리스트 방식으로 구현하려고 합니다!
이 문제같은 경우 왼쪽 자식과 오른쪽 자식을 각각 지정해주는데 이런 경우에는 어떻게 구현해야 할까요..?

**Comment by yujin1292** [comment]
이진 트리를 표현할 때 인접리스트를 사용하게 될 경 Left Child와 Right Child를 구분하지 못한다는 단점이 있습니다! 
따라서 `G[N][2]` 형태의 인접행렬이 좀 더 간편할것같아요!

아니면 struct를 이용하거나, class 를 만들어서 사용해도 괜찮고요

```c++
typedef struct node {
	char lChild = '.';
	char rChild = '.';
};

node G[26];

int main() {

	int n;
	cin >> n;

	for (int i = 0; i < n; i++) {
		char cur, lchild, rchild;
		cin >> cur >> lchild >> rchild;
		G[cur - 'A'].lChild = lchild;
		G[cur - 'A'].rChild = rchild;
	}

	return 0;
}
```

**Comment by arami98** [comment]
감사합니다 참고해서 해결 했어요!
