### ISSUE TITLE
n-queen문제

### ISSUE THREAD

**Issue by arami98** [yujin1292/BreakingCodingTest#34]
올려주신 자료 봤는데도 이해가 잘 안 되네여,, 부가 설명 부탁드립니다..!

**Comment by yujin1292** [comment]
## intro
이 문제는 대표적인 백트래킹 문제이고,  풀기위해서는 두가지의 이해가 필요한데요
1. 퀸의 움직일수 있는 방향
2. 행렬에서의 대각선 방향의 인덱스 특징 (?)

일단 퀸은 이동하는 칸의 수와 상관없이, 8방으로 움직일 수 있다는건 알고있을거에요!

우리는 (0,0)에서 시작해서 점차적으로 퀸을 놓아보는 러프한 함수를 한번 짜볼게요 퀸이 놓여진 위치를 알아야하기때문에 `x 좌표`, `y 좌표` 를 알아야될태고 몇개의 퀸을 놓았는지 또한알아야 하니 `int count` 또한 가지고 있다고 해볼게요.

큼직한 로직을 보면 다음에 움직일 수 있는 `nextCol`, `nextRow`를 설정하고 방문 표시를하고, `dfs(nextRow,nextCol,count+1)`를 실행하고 함수가끝나면 복구하는 방식을 사용할거에요.. 그러나 이 문제는 대표적인 백트래킹 문제이기에  `어떻게 최적화 할것인가?!` 가 키포인트라고 생각이듭니다..

## 가지치기(최적화) => 백트래킹! 
평소처럼 visit[N][N] 하나로만 생각한다면 `팔방으로 퀸이 놓여있는지 체크하는함수`를 이용해서 일일히 체크해야하니  엄청나게 느려질거에요..


만약에 퀸을` board[row][col]`에 놓았다면,  `세로(col)`,`가로(row)` 로는 더이상 놓을수가 없습니다. 또한 `우대각 ``좌대각` 방향으로도 놓을수 없는데, 행렬의 특성상` (row+col) `과` (row-col) `로 구분이 가능하답니다~ 이 조건들을 모두 이용한다면 좀더 효율적이겠죠?

그렇다면 전에는 하나만 사용했떤 visited배열이 위의 조건을 이용해 각각 배열로처리하면 O(1)로 빠르게 판단할수 있을거에요
ex) ```col[r] = true```  r 번째 col는 퀸이 놓여있음

``` c++
void dfs( int row, int col, int count){
  if(중단 조건){
     return;
  }

  int nextRow, nextCol;
  for(  ) { // 다음 위치를 반복적으로 저장
      if( nextRow, nextCol에 방문 가능하다면){
        여러개의 visited 조건 = true;  /
        dfs(nextRow, nextCol, count+1);
        여러개의 visited 조건 = false; // ( 다음 방문을 위해 복구)
      }
  }
}
```

세줄 요약하면,
1. 단순 dfs 문제처럼 생각해라
2. visited 체크가 조금 특별할 뿐이다!
3. 아주 많은 경우의수가 존재하니, 최대한 가지치기를 진행하면 좋다

**Comment by arami98** [comment]
`만약에 퀸을 board[row][col]에 놓았다면, 세로(col),가로(row) 로는 더이상 놓을수가 없습니다. `

이 부분이 잘 이해가 안되는데 같은 줄에 있더라도 놓을 수 있는 경우가 있는 것 아닌가요..?ㅠㅠ

**Comment by yujin1292** [comment]
만약에 `board[x][y]` 에 퀸이 놓여져있다면

`board[x][??]`과, `board[??][y]` 는 퀸을 더이상 놓을수가없죠! 왜냐면 퀸이 움직 수 있는 위치이기 때문이에요~

핑크색 형광펜으로 표시한 위치는 퀸을 더이상 놓을수 없는곳이니까여
![image](https://user-images.githubusercontent.com/27190708/144177047-3fdac6cc-c329-442a-ba54-99b966348796.png)
