### ISSUE TITLE
LIS 관련 정리 

### ISSUE THREAD

**Issue by yujin1292** [yujin1292/BreakingCodingTest#72]
제가 LIS 복습하면서 정리한 내용들인데용
한번 꼬옥 .. 읽어보면 좋을것 같아서 링크 남깁니다 ~ ! !! ! 

읽으셨으면 댓글남겨주세용 다읽으셨으면 Issue close 하게요~!

@jeongiin  @j-miiin 

https://yujin2.notion.site/Longest-Increasing-Subsequence-b6d7bad7a1be4b268e2b0d002188cc58

**Comment by jeongiin** [comment]
확인했습니다 자료 공유 감사합니다 :)

**Comment by j-miiin** [comment]
에구 늦었네요 다 읽었습니다~! 좋은 자료 감사합니당!!
