### ISSUE TITLE
은근 중요한 위상정렬 

### ISSUE THREAD

**Issue by yujin1292** [yujin1292/BreakingCodingTest#80]
시즌2때 짚고 넘어갔어야됐는데 . . . 까먹고 진도못나간 위상정렬이에요 흑흑
알아두면 너무너무 좋은 ... 그런녀석입니다 
제가 공부하면서 참고했던 링크 남겨둡니다 

https://blog.naver.com/ndb796/221236874984

@j-miiin  @jeongiin

**Comment by j-miiin** [comment]
이런 정렬도 있었군요 처음 들어보는데 아직도 공부할게 한참 많다는걸 느낍니당ㅠㅠ 자료 공유 감사합니다~!
